server:
  port: 8765
spring:
  application:
    name: spring-aop
  datasource:
    url: jdbc:mysql://localhost:3306/db_school?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true&useSSL=false
    hikari:
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.zjhang.dao.StudentMapper: debug
    com.zjhang.dao.OperateLogMapper: debug